codinguser/gnucash-android

- app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
Fix #279 .
#279 is caused by the current QIF export logic. When there's N splits in a transaction, only N-1 is recorded in QIF export, as the last one is auto-balanced. When there's only one split, it got lost.
Add special handling for single split transaction in QIF export.
This may also be related to #253 . When I tested for this bug, I found that when there's no transaction to be exported (e.g. all transactions have only split), the export file is not created at all.
> QIF export for sinlgle split entry

- app/src/main/java/org/gnucash/android/model/Money.java
- app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
Auto balance transaction as `saveNewTrasaction`.
> auto balance transaction

- app/src/main/res/values-zh/strings.xml
Update zh-cn translated to 1.5.5
> Keep zh-cn translated to 1.5.5	

- app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
> Bugfix 315: The export progress dialog is never dismissed

- app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
> Feature #329: Search also through ancestors for default transfer account

- app/src/main/java/org/gnucash/android/ui/settings/SettingsActivity.java
> Fix crash if no application is selected to choose a file to import accounts.

- app/src/main/res/values-uk/strings.xml
Regarding graphs. The pie chart is really buggy. I'll fix it as soon as possible.
> Ukrainian translation

- app/src/main/java/org/gnucash/android/ui/BaseDrawerActivity.java
> Migrate to the non-deprecated version of ActionBarDrawerToggle

- app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/LineChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
So far implemented support for time ranges. I will push some changes/refactoring and grouping by month/year/all in a few days.
> Charts time ranges

- app/src/main/java/org/gnucash/android/ui/report/LineChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
Also fixed crash on screen orientation change.
> Grouping for line chart 

- app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/LineChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/PieChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
- app/src/main/res/menu/chart_actions.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es-rMX/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-hu/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb/strings.xml
- app/src/main/res/values-nl/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-uk/strings.xml
- app/src/main/res/values-zh-rTW/strings.xml
- app/src/main/res/values-zh/strings.xml
- app/src/main/res/values/strings.xml
The bar char legend on bottom of the chart cause the app crash. It looks like a bug with wrapping labels. So I moved it to right side.
> Bar chart grouping

- app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
propagation of default transfer account when editing the transaction is already implemented.
> propagate default transfer account in account edit

- app/src/main/java/org/gnucash/android/db/AccountsDbAdapter.java
- app/src/main/java/org/gnucash/android/db/SplitsDbAdapter.java
- app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java
- app/src/main/java/org/gnucash/android/ui/transaction/TransactionsActivity.java
If there is a price exists in the price table, the amount is converted according to the price. Otherwise, the amount in other currencies is ignored.
Balances of custom currencies are ignored.
> calculate multi-currency account balance

- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values/donottranslate.xml
> Update french translation

- app/src/main/res/values-pl/strings.xml
* new labels
* fixed plurals
* replaced few ... with …
> updated Polish translations

- app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/LineChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/PieChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportSummaryFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java
- Fixed reports with time period of current month don’t include most recent transactions
- Fixed a time period sometime doesn’t save after changes
- Eliminate redundant repaints of charts
- Moved bar chart legend to bottom of the chart
> Report recent transactions and others

- app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
Added code to compute the most used currency in transactions, and set it as default.
> set default currency as the most used currency

- app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
Fixes https://github.com/codinguser/gnucash-android/issues/433
> Bugfix 433 Crash if intent to open a file is canceled

- app/src/main/res/drawable/numeric_button.xml
- app/src/main/res/layout/fragment_numeric_keyboard.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Tried to improve the look of the passcode lockscreen...
Old | New
----- | ------
> Improve passcode UI

- app/src/main/java/org/gnucash/android/export/Exporter.java
> Bugfix 448 OFX export fails with FileNotFoundException

- app/src/androidTest/java/org/gnucash/android/test/ui/CalculatorEditTextTest.java
- app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
Fixes #417.
All about this issue has been very tricky, so please, check nothing new gets broken with the fix.
> Bugfix 417: Sometimes amount text boxes in the split editor fail getting the focus

- app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
Although they're not used Android documentation recommends having them:
http://developer.android.com/training/custom-views/create-view.html
> Readd unused methods to CalculatorEditText.

- app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/PieChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportSummaryFragment.java
> Bugfix 495 -  Bug: All colors in reports are grey

- README.md
> Document GitHub releases as a way to obtain the application

- README.md
Do not assume `.` is in the PATH (it should not)
> Fix instructions to run gradlew

- app/src/main/java/org/gnucash/android/ui/transaction/dialog/TransferFundsDialogFragment.java
- app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
- app/src/main/java/org/gnucash/android/util/AmountParser.java
- app/src/test/java/org/gnucash/android/test/unit/util/AmountParserTest.java
> Bugfix 505: NullPointerException on empty value in currency-converted amount

- app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
- app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
- app/src/main/java/org/gnucash/android/db/adapter/CommoditiesDbAdapter.java
- app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
- app/src/main/java/org/gnucash/android/model/Account.java
- app/src/main/java/org/gnucash/android/receivers/AccountCreator.java
- app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
- app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
- app/src/main/java/org/gnucash/android/ui/report/ReportsOverviewFragment.java
- app/src/main/java/org/gnucash/android/ui/report/barchart/StackedBarChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/linechart/CashFlowLineChartFragment.java
- app/src/main/java/org/gnucash/android/ui/report/piechart/PieChartFragment.java
- app/src/test/java/org/gnucash/android/test/unit/model/AccountTest.java
This pull request is a step towards removing use of Currency, at least for the cases where Commodity is more appropriate. More PRs will be needed to complete the removal from other classes. This will avoid duplication of information and confusion caused by the use of two similar classes.
> Replace uses of Currency with Commodity in Account

- app/src/main/java/org/gnucash/android/db/adapter/ScheduledActionDbAdapter.java
- app/src/test/java/org/gnucash/android/test/unit/db/ScheduledActionDbAdapterTest.java
> Bugfix 512:  Listing scheduled actions fails with NullPointerException

- app/src/main/java/org/gnucash/android/model/ScheduledAction.java
- app/src/test/java/org/gnucash/android/test/unit/model/ScheduledActionTest.java
It looks like a copy-paste mistake. I doesn't seem there was any bug caused by this.
> Fix setting Recurrence.mPeriodEnd from ScheduledAction.setEndTime()

- app/src/test/java/org/gnucash/android/importer/GncXmlHandlerTest.java
- app/src/test/resources/simpleTransactionImport.xml
- app/src/test/resources/testAccountsImport.xml
Just a pair of simple tests to get started.
> Add unit tests for importing of GnuCash XML files.

- app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
- app/src/test/java/org/gnucash/android/importer/GncXmlHandlerTest.java
- app/src/test/resources/bug562_scheduledTransactionImportedWithImbalancedSplits.xml
- app/src/test/resources/testImportSimpleScheduledTransaction.xml
> Bugfix 562: Scheduled transaction imported with imbalanced splits

- app/src/main/java/org/gnucash/android/ui/settings/dialog/OwnCloudDialogFragment.java
> Make success text color green in ownCloud dialog

- app/src/main/java/org/gnucash/android/model/ScheduledAction.java
- app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
- app/src/test/java/org/gnucash/android/test/unit/model/ScheduledActionTest.java
- app/src/test/java/org/gnucash/android/test/unit/service/ScheduledActionServiceTest.java
It still end up a bit ugly, but I guess good enough...
Fixes #591 and #594
> Bugfix 591 & 594: Fix issues with scheduled exports running too much or not at all

- app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
- app/src/test/java/org/gnucash/android/test/unit/service/ScheduledActionServiceTest.java
I hope this time it's fixed for real. Please, check nothing else has slipped through.
Fixes #604
> Bugfix 604: Scheduled exports aren't executed if they're checked before the next run

- app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
Should fix #571. It's been too easy, so I'm not really sure :)
> Bugfix 571: Multi-currency transactions are ignored by QIF

- app/src/main/java/org/gnucash/android/ui/util/dialog/DateRangePickerDialogFragment.java
I am using this app for a month now and was bothered that the date range was not properly set when I was trying to enjoy the pie chart report. This small fix does the trick for me. Since I have only little experience with git and I am completely new to github I want to apologize in advance if I did something wrong with the workflow.
> proper handling of custom date range selections - fixes #611

- app/src/androidTest/java/org/gnucash/android/test/ui/AccountsActivityTest.java
- app/src/main/java/org/gnucash/android/db/adapter/AccountsDbAdapter.java
- app/src/main/java/org/gnucash/android/db/adapter/TransactionsDbAdapter.java
- app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
- app/src/main/java/org/gnucash/android/model/Transaction.java
- app/src/main/java/org/gnucash/android/receivers/TransactionRecorder.java
- app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java
I was a bit wary about the second commit (86f2343), so I'd feel better if you confirmed it's ok.
> Currency-commodity migration changes

- app/src/main/java/org/gnucash/android/ui/util/widget/CalculatorEditText.java
- app/src/main/res/layout/fragment_transaction_form.xml
Long-press on amount field showed built-in keyboard. fixes #689
> Fix bug #689

- app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
#777 Now it's possible to load xml from desktop version 3.0
> Added ability to load GNUCash v. 3.0 xml

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Builds successfully in Android Studio and I was able to run it on my phone
> Update gradle wrapper to 4.4 and plugin to 3.1.4
