codinguser/gnucash-android

app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java

When an account tree is created with gnucash-android (not imported), ROOT account may not exist. Thus in exported XML files, top level accounts do not have parent, causing the parentAcount to be null.
Added a check that will treat all accounts without a parent to be top level.
Should fix #295 .

import with null parent

---

app/src/main/java/org/gnucash/android/db/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/ui/util/AccountBalanceTask.java
app/src/main/java/org/gnucash/android/ui/widget/WidgetConfigurationActivity.java

When calculating balance in AccountBalanceTask and Widge, only consider transactions whose time stamp is before the system time. ‘Future' transactions are ignore.
Widget is not tested.

future transactions are not included in balance calculation

---

app/src/main/java/org/gnucash/android/db/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java

Stop importing (by throw) if:
1) The import XML has no ROOT, and db is not empty.
This is a backup restore. Everything should be cleared before import.
2) The import XML has multiple ROOT
There's an error in import XML
3) The import XML has one ROOT, but it is different form the ROOT in the DB, or DB has no ROOT
What imported is a different book from the one in the DB.
See discussion in #189.

Prevent importing different ROOT account

---

app/src/main/res/values-zh/strings.xml

Keep zh_CN translated(report,side bar,perference).

Keep zh_CN translated(report,side bar,perference).

---

app/src/main/java/org/gnucash/android/db/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/db/DatabaseHelper.java
app/src/main/java/org/gnucash/android/db/MigrationHelper.java

710c2a9
Remove `static` in `DatabaseAdapter` log tag. With `static`, different dbAdatpers will share one Log TAG. This will make the log message unclear.
I saw some messages from `AccountsDbAdapter` mis-tagged as from `ScheduledTransactionsDbAdapter`.
ba4438c
ROOT account's parents are assumed to be null. Setting ROOT account as its own parent will cause some infinite loops in the App.
This caused an infinite loop in `TransactionsActivity.onResume()`, which may be related to the black screen problem.
2fc46fa
Auto-balancing transactions during import will loop through all transactions, this may cost a lot of time.
This is rewritten as only select unbalanced transactions, and without constructing a `Transaction` instance, which saves a lot of time for book with a lot of transactions. …

Fix some migration problems

---

app/src/main/java/org/gnucash/android/ui/account/AccountsActivity.java

As the elevation is already set in the layout (app:elevation), we can
remove the redundant call.
Fixes #352

Avoid crash due to setElevation() not supported devices with API < 21.

---

app/src/main/java/org/gnucash/android/db/SplitsDbAdapter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlHelper.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/model/Money.java
app/src/main/java/org/gnucash/android/model/Split.java
app/src/main/java/org/gnucash/android/model/Transaction.java

Some notes:
The account balance should be the same with gnucash even with multi-currency transactions, if no price table exists in the desktop version. The price table can be deleted from the desktop version.
Split.setValue will NOT set quantity any more. If quantity is null it will print an error message. Remove this check and error message when everyone knows this.
During import, the amount format should not contain any special characters according to gnucash XML doc. So I removed the special treatment for special characters.
Auto balance for multi-currency should work for gnucash generated XML files, but it won't work for old GNCA exports. Extra splits would be created.

some multi currency support based on value and quantity

---

app/src/main/java/org/gnucash/android/db/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/db/TransactionsDbAdapter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/importer/GncXmlImporter.java

Deleting transactions without deleting the splits first takes 300 times more time on my book.

clear the database (much) faster

---

app/src/main/java/org/gnucash/android/ui/transaction/SplitEditorFragment.java

The generated UUID for a new split is in the wrong format, which will result in an erroneous split when the exported XML is opened by GnuCash desktop.

fix wrong uid in new split

---

app/src/main/java/org/gnucash/android/db/DatabaseAdapter.java
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java

quick fix to #436 .
It is caused by REPLACE sql command. REPLACE will delete then insert, and the deletion would cause the transactions to be deleted due to ON DELETE CASCADE on the foreign key constraint.

fix the bug that modify account name will delete all transaction under the account

---

app/src/main/res/values-zh-rCN/strings.xml

Updated res/values-zh-rCN/strings.xml. Changed the confusing "Owncloud" to " share to"

Modify "Owncloud" in export destinations

---

app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/account/DeleteAccountDialogFragment.java
app/src/main/java/org/gnucash/android/ui/colorpicker/ColorPickerPalette.java
app/src/main/java/org/gnucash/android/ui/report/BaseReportFragment.java
app/src/main/java/org/gnucash/android/ui/report/sheet/BalanceSheetFragment.java
app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

This pull request is focused on resolving occurrences of Sonar rule " UselessParenthesesCheck -     Useless parentheses around expressions should be removed to prevent any misunderstanding". You can find more information about the issues here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
Sameer Misger

Fixing squid:UselessParenthesesCheck-Useless parentheses around expressions should be removed to prevent any misunderstanding

---

app/src/main/java/org/gnucash/android/db/AccountsDbAdapter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/model/Account.java
app/src/main/java/org/gnucash/android/ui/account/AccountFormFragment.java
app/src/main/java/org/gnucash/android/ui/report/BarChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/PieChartFragment.java
app/src/main/java/org/gnucash/android/ui/report/ReportSummaryFragment.java
app/src/test/java/org/gnucash/android/test/unit/model/AccountTest.java

I've applied the idea of the [Null object pattern](https://en.wikipedia.org/wiki/Null_Object_pattern) to some methods of Account. It simplifies the code of its clients by not having to check for null values.
If it's ok, I plan to send more small pull requests like this one, trying to simplify the code little by little. This would make the code easier to understand, as sometimes I have difficulties due to the many conditionals.

Avoid returning nulls from some Account methods

---

app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java

AccountsListFragment didn't save it state that caused to displaying identical fragments in ViewPager.
Steps to reproduce:
- open homescreen (AccountsActivity);
- check ViewPager fragments;
- rotate device;
- check ViewPager fragments, they all will have mDisplayMode with value TOP_LEVEL.

Fix saving state in AccountsListFragment

---

app/src/main/java/org/gnucash/android/model/Price.java
app/src/test/java/org/gnucash/android/test/unit/model/PriceTest.java

Fixes a regression introduced in 66cc533 (bugfix #479) in which the numerator/denominator division fails with an `ArithmeticException` if no `MathContext` is provided. Somehow I missed it when moving code around.
Fixes Crashlitics issue [#196](https://fabric.io/gnucash/android/apps/org.gnucash.android/issues/571b4a95ffcdc04250f98ba03)

Avoid Price.toString() failing for certain values of numerator/denominator.

---

app/build.gradle
app/src/main/java/org/gnucash/android/app/GnuCashApplication.java

Adds [Stetho](http://facebook.github.io/), a debug bridge that, among other things, allows to access the database and preferences of the application through Chrome developer tools.
The database access is especially useful. It allows to browse the tables and send SQL queries.
To make it simple, I've included the library in all builds, although at runtime it's only enabled for debug builds. If you find it useful and want it to be included only for debug builds, I can set it up with a separate debug Application like explained [here](http://stackoverflow.com/a/30172663).

Enable remote debugging from Chrome developer tools

---

app/src/main/java/org/gnucash/android/model/Recurrence.java
app/src/test/java/org/gnucash/android/test/unit/model/RecurrenceTest.java

Fixes #526 
I haven't implemented going through `TransactionDetailFragment` first yet. I've found some bugs in the way that I'd like to fix first.
By the way, I've noticed the start and end periods are stored both in `scheduled_actions` and `recurrences` tables. Is this duplicated for convenience or should we remove one of them?

Bugfix 526: Opening a scheduled transaction to view causes app to crash

---

app/src/main/java/org/gnucash/android/ui/transaction/TransactionFormFragment.java

Introduced in 96a2045. I guess you meant this condition instead.
I haven't added a tests as, apart from not being able to run them on my phone yet, I'd say `TransactionsActivityTest.testAutoBalanceTransactions` should fail.

Bugfix 577: Can't save transactions on single entry mode

---

app/src/main/java/org/gnucash/android/service/ScheduledActionService.java
app/src/test/java/org/gnucash/android/test/unit/service/ScheduledActionServiceTest.java

Bugfix 583:   Scheduled exports are always executed twice a day

---

app/src/main/java/org/gnucash/android/db/MigrationHelper.java
app/src/main/java/org/gnucash/android/db/adapter/RecurrenceDbAdapter.java
app/src/main/java/org/gnucash/android/export/xml/GncXmlExporter.java
app/src/main/java/org/gnucash/android/importer/GncXmlHandler.java
app/src/main/java/org/gnucash/android/model/Budget.java
app/src/main/java/org/gnucash/android/model/PeriodType.java
app/src/main/java/org/gnucash/android/model/Recurrence.java
app/src/main/java/org/gnucash/android/model/ScheduledAction.java
app/src/main/java/org/gnucash/android/ui/util/RecurrenceParser.java
app/src/test/java/org/gnucash/android/test/unit/db/ScheduledActionDbAdapterTest.java
app/src/test/java/org/gnucash/android/test/unit/model/RecurrenceTest.java
app/src/test/java/org/gnucash/android/test/unit/model/ScheduledActionTest.java

PeriodType enum values should be immutable. The instances are shared so,
once a value is got, it shouldn't be possible to set its fields.
This was causing some tests to fail, as they were getting the same
instance but setting different values for the field.

Move mutable field PeriodType.mMultiplier to Recurrence.

---

app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java

The number used to calculate whether a widget is red or green should be the same value as the one that is displayed. It was instead calling a (buggy) method which calculated a different balance to the one displayed. This patch fixes it to determine the colour using the same value as the one it is displaying.
This should fix issue #184.

Fix widgets with negative values being green

---

app/src/main/java/org/gnucash/android/receivers/TransactionAppWidgetProvider.java
app/src/main/java/org/gnucash/android/ui/common/UxArgument.java
app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java
app/src/main/res/layout/widget_configuration.xml
app/src/main/res/values/strings.xml

This commit adds an option to widgets which lets you hide the balance of the account that the widget is displaying. If you have set a passcode then the widget will default to not showing the account balance, otherwise it will default to showing the account balance.
This resolves part of #598.

Make widgets able to hide the account balance

---

app/src/main/java/org/gnucash/android/ui/wizard/FirstRunWizardActivity.java

If the screen rotates while the first-run wizard is open then GnuCash will crash with a NullPointerException. To avoid this we need to make sure we create our WizardModel before it is used to try to restore our page.
This should fix #596.

Fix first run wizard crashes on screen rotation

---

app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java
app/src/main/res/layout/widget_4x1.xml
app/src/main/res/values/strings.xml

When a widget is created for a placeholder account we change the "add transaction" button on the widget to instead be an "information" icon, which opens up the account details when clicked.
Should fix #592.

Change widget button to open placeholder accounts

---

app/src/main/java/org/gnucash/android/receivers/TransactionAppWidgetProvider.java
app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java

If we can't find the new "hide account balance" setting, we should default to the old behaviour: show the account balance.

Make widgets backwards compatible

---

app/src/main/java/org/gnucash/android/receivers/TransactionAppWidgetProvider.java
app/src/main/java/org/gnucash/android/ui/homescreen/WidgetConfigurationActivity.java

Instead of saving everything into a SharedPreferences object associated with each book, this saves widget preferences into a separate SharedPreferences object each.
Some effort is make to ensure that this is backwards compatible, so if there are settings in the old format they will be copied into the new format before being erased.
This should resolve #607, using the approach that I prefer.

Move widget config into separate SharedPreferences

---

app/src/main/java/org/gnucash/android/db/adapter/RecurrenceDbAdapter.java
app/src/main/java/org/gnucash/android/model/Recurrence.java
app/src/main/java/org/gnucash/android/ui/util/RecurrenceParser.java

Fixes #617 
There some are important changes, so I thought you might want to review it.
Instead of storing the days of the week as a string ("MO;TH") in `mByDay`, which is painful to work with, I've changed it to store as a List of Calendar constants (`Calendar.MONDAY`) instead. If later we want to support specific days in the month, we can just change the list type to some other class to hold the new information.
As this was meant for hotfix/patches, I haven't changed the database structure but, in my opinion, we should think of storing `recurrence_byday` in a separate table. Apart from not conforming with the first normal form, the parsing of the column (`RecurrenceDbAdapter.{byDaysToString,stringToByDays}` ) makes it awkward to work with.

Bugfix 617: Weekly scheduled exports are listed with the wrong day

---

app/src/main/java/org/gnucash/android/ui/report/ReportsActivity.java

For an unknown reason the `onAttachFragment()` is being called from parent's `onCreate()`
This fix makes sure the report type is preserved across rotation so when the `updateReportTypeSpinner()` is called it does nothing because there is no changes in the report type
* fixes codinguser/gnucash-android#633

Preserve report type across rotation

---

app/src/main/java/org/gnucash/android/db/DatabaseSchema.java
app/src/main/java/org/gnucash/android/db/MigrationHelper.java
app/src/main/java/org/gnucash/android/ui/account/AccountsListFragment.java

Fixes #654 
At the end I've chosen the easiest path to avoid some problems or changing too much code.

Bugfix 654: App crashes when trying modify account if default transaction account no longer exist

---

app/src/main/res/layout/fragment_transaction_form.xml

Less typing is better :)
I guess you just left the default. I can't find any reason for having to type two characters instead of one but, just in case, I leave it for you to approve.

Start autocompleting transactions with one character

---

app/src/main/java/org/gnucash/android/model/ScheduledAction.java
app/src/test/java/org/gnucash/android/test/unit/model/ScheduledActionTest.java
app/src/test/java/org/gnucash/android/test/unit/service/ScheduledActionServiceTest.java

Am I late for 2.2?
Please, check I haven't missed any corner case :)

Bugfix 641: Weekday is ignored in scheduled exports

---

app/src/main/java/org/gnucash/android/export/ExportAsyncTask.java
app/src/main/java/org/gnucash/android/export/qif/QifExporter.java
app/src/main/java/org/gnucash/android/util/FileUtils.java

Zip multiple exported QIF files into one for all export destinations

---

app/src/main/java/org/gnucash/android/ui/settings/BookManagerFragment.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllAccountsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteAllTransactionsConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DeleteBookConfirmationDialog.java
app/src/main/java/org/gnucash/android/ui/settings/dialog/DoubleConfirmationDialog.java
app/src/main/res/layout/dialog_double_confirm.xml
app/src/main/res/values/strings.xml
app/src/test/java/org/gnucash/android/test/unit/model/TransactionTest.java

I haven't found any other dialog that should have double confirmation, apart from the ones mentioned on the issue, but I might've missed some.
Fixes #544.

Bugfix 544: Add dialog with extra checkbox for irreversible actions

---

app/build.gradle
app/src/main/res/values/styles.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

A few things to make the project build with Android Studio 3:
-  updating the build tools
- adding flavor dimensions
- handling output file name
- updating Gradle plugin & Gradle

Android Studio 3 compatibility

---

app/src/main/res/layout/widget_4x1.xml

I haven't done much with themes, styles and alike. So I'm not sure if this is the best way to fix the problem.
Reported on [Google+ group](https://plus.google.com/117605068428491461489/posts/92CVFy3ASzv).

Fix widget black text on black background on newer Android versions

---

app/src/main/java/org/gnucash/android/app/GnuCashApplication.java
app/src/main/java/org/gnucash/android/db/adapter/BooksDbAdapter.java
app/src/test/java/org/gnucash/android/test/unit/db/BooksDbAdapterTest.java

The fix implemented in c27f763 didn't solve the issue. It now fails because the books database is empty. This pull request will hopefully solve the problem, unless there's been real data loss.
Fixes http://crashes.to/s/d7c34870c8d

Recover from empty books database

---

app/src/main/java/org/gnucash/android/ui/transaction/ScheduledActionsListFragment.java

fixed add button disappearing after rotation

---

app/src/main/res/raw-hr/default_accounts.gnucash

Initial release of the common croatian accounts. These are the same as the ones I did for the desktop version of GnuCash, plus specifying the account colors defined in the Android version.

Initial release of croatian accounts

---

app/src/main/java/org/gnucash/android/export/csv/CsvTransactionsExporter.java

CSV exporting was taking tens of minutes on my phone, for only around 120 exported transactions, and a database containing 2 years worth of personal finances.
This PR fixes it. Technical details are in commit messages, but basically: the code fetched all transactions from one account for every single exported split. That meant easily tens of thousands or even hundreds of thousands requests for one export.

Fix slow CSV exports

---

README.md

While "Licence" is an allowed spelling, the rest of the paragraph uses "License" so switch to that for consistency.

Use "License" everywhere for consistency

---

app/src/main/java/org/gnucash/android/ui/common/BaseDrawerActivity.java
app/src/main/java/org/gnucash/android/ui/settings/PreferenceActivity.java

This fix allows to close the main menu by clicking on the back button
When navigating in the Preferences Activities, clicking on the "Home" button (which appears with a left arrow) acts the same as clicking on the back button : It unpops each Activity.

Fixes #857 - Close Main Navigation Menu with Back button
